//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AssetTransition.java
//  @ Date : 2012-11-15
//  @ Author : 
//
//



package com.avit.getDate.bean;

import java.io.Serializable;
import java.sql.Timestamp;


public class AssetTransition implements Serializable  {
	
	private static final long serialVersionUID = 1L;
	
	private String assetId;
	private String productCode;
	private String productOfferingCode;
	private String contentPackageCode;
	private String contentCode;
	private Integer chargeType;
	private Integer contentType;
	private Integer productType;
	private String parentAssetId;
	private String assetName;
	private String assetDesc;
	private String title;
	private String year;
	private String keyword;
	private String rating;
	private String runTime;
	private String displayRunTime;
	private String posterUrl;
	private String director;
	private String actor;
	private Timestamp createTime;
	private Timestamp modifyTime;
	private String state;
	private String price;
	private String entryCount;
	private String category;
	private String businessCode;
	private String poSpecCode;
	private String poSpecName;
	private String operationCode;
	private String serviceCode;
	private String serviceName;
	private Integer contentOrder;
	private String posterWidthHeight;
	private String vodFormat;
	private String ottFormat;
	private String firstSpell;
	private String validStart;
	private String validEnd;
	private String genre;
	/** 川网扩展字段 */
	private String providerId;
	private String providerAssetId;
	
	private String productOfferingName;//商品名称
	// Constructors

	/** default constructor */
	public AssetTransition(){
	}

	public AssetTransition(AssetTransition a, String productOfferingName) {
		this.assetId = a.assetId;
		this.productCode = a.productCode;
		this.productOfferingCode = a.productOfferingCode;
		this.contentPackageCode = a.contentPackageCode;
		this.contentCode = a.contentCode;
		this.chargeType = a.chargeType;
		this.contentType = a.contentType;
		this.productType = a.productType;
		this.parentAssetId = a.parentAssetId;
		this.assetName = a.assetName;
		this.assetDesc = a.assetDesc;
		this.title = a.title;
		this.year = a.year;
		this.keyword = a.keyword;
		this.rating = a.rating;
		this.runTime = a.runTime;
		this.displayRunTime = a.displayRunTime;
		this.posterUrl = a.posterUrl;
		this.director = a.director;
		this.actor = a.actor;
		this.createTime = a.createTime;
		this.modifyTime = a.modifyTime;
		this.state = a.state;
		this.price = a.price;
		this.entryCount = a.entryCount;
		this.category = a.category;
		this.businessCode = a.businessCode;
		this.poSpecCode = a.poSpecCode;
		this.poSpecName = a.poSpecName;
		this.operationCode = a.operationCode;
		this.genre = a.genre;
		this.productOfferingName = productOfferingName;
	}
	

	/**
	 * @return the assetId
	 */
	public String getAssetId() {
		return assetId;
	}
	/**
	 * @param assetId the assetId to set
	 */
	public void setAssetId(String assetId) {
		this.assetId = assetId;
	}
	/**
	 * @return the productCode
	 */
	public String getProductCode() {
		return productCode;
	}
	/**
	 * @param productCode the productCode to set
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}
	/**
	 * @return the productOfferingCode
	 */
	public String getProductOfferingCode() {
		return productOfferingCode;
	}
	/**
	 * @param productOfferingCode the productOfferingCode to set
	 */
	public void setProductOfferingCode(String productOfferingCode) {
		this.productOfferingCode = productOfferingCode;
	}
	/**
	 * @return the contentPackageCode
	 */
	public String getContentPackageCode() {
		return contentPackageCode;
	}
	/**
	 * @param contentPackageCode the contentPackageCode to set
	 */
	public void setContentPackageCode(String contentPackageCode) {
		this.contentPackageCode = contentPackageCode;
	}
	/**
	 * @return the contentCode
	 */
	public String getContentCode() {
		return contentCode;
	}
	/**
	 * @param contentCode the contentCode to set
	 */
	public void setContentCode(String contentCode) {
		this.contentCode = contentCode;
	}
	/**
	 * @return the chargeType
	 */
	public Integer getChargeType() {
		return chargeType;
	}
	/**
	 * @param chargeType the chargeType to set
	 */
	public void setChargeType(Integer chargeType) {
		this.chargeType = chargeType;
	}
	/**
	 * @return the contentType
	 */
	public Integer getContentType() {
		return contentType;
	}
	/**
	 * @param contentType the contentType to set
	 */
	public void setContentType(Integer contentType) {
		this.contentType = contentType;
	}
	/**
	 * @return the productType
	 */
	public Integer getProductType() {
		return productType;
	}
	/**
	 * @param productType the productType to set
	 */
	public void setProductType(Integer productType) {
		this.productType = productType;
	}
	/**
	 * @return the parentAssetId
	 */
	public String getParentAssetId() {
		return parentAssetId;
	}
	/**
	 * @param parentAssetId the parentAssetId to set
	 */
	public void setParentAssetId(String parentAssetId) {
		this.parentAssetId = parentAssetId;
	}
	/**
	 * @return the assetName
	 */
	public String getAssetName() {
		return assetName;
	}
	/**
	 * @param assetName the assetName to set
	 */
	public void setAssetName(String assetName) {
		this.assetName = assetName;
	}
	/**
	 * @return the assetDesc
	 */
	public String getAssetDesc() {
		return assetDesc;
	}
	/**
	 * @param assetDesc the assetDesc to set
	 */
	public void setAssetDesc(String assetDesc) {
		this.assetDesc = assetDesc;
	}
	/**
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}
	/**
	 * @param title the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}
	/**
	 * @return the year
	 */
	public String getYear() {
		return year;
	}
	/**
	 * @param year the year to set
	 */
	public void setYear(String year) {
		this.year = year;
	}
	/**
	 * @return the keyword
	 */
	public String getKeyword() {
		return keyword;
	}
	/**
	 * @param keyword the keyword to set
	 */
	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}
	/**
	 * @return the rating
	 */
	public String getRating() {
		return rating;
	}
	/**
	 * @param rating the rating to set
	 */
	public void setRating(String rating) {
		this.rating = rating;
	}
	/**
	 * @return the runTime
	 */
	public String getRunTime() {
		return runTime;
	}
	/**
	 * @param runTime the runTime to set
	 */
	public void setRunTime(String runTime) {
		this.runTime = runTime;
	}
	/**
	 * @return the displayRunTime
	 */
	public String getDisplayRunTime() {
		return displayRunTime;
	}
	/**
	 * @param displayRunTime the displayRunTime to set
	 */
	public void setDisplayRunTime(String displayRunTime) {
		this.displayRunTime = displayRunTime;
	}
	/**
	 * @return the posterUrl
	 */
	public String getPosterUrl() {
		return posterUrl;
	}
	/**
	 * @param posterUrl the posterUrl to set
	 */
	public void setPosterUrl(String posterUrl) {
		this.posterUrl = posterUrl;
	}
	/**
	 * @return the director
	 */
	public String getDirector() {
		return director;
	}
	/**
	 * @param director the director to set
	 */
	public void setDirector(String director) {
		this.director = director;
	}
	/**
	 * @return the actor
	 */
	public String getActor() {
		return actor;
	}
	/**
	 * @param actor the actor to set
	 */
	public void setActor(String actor) {
		this.actor = actor;
	}
	/**
	 * @return the createTime
	 */
	public Timestamp getCreateTime() {
		return createTime;
	}
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}
	/**
	 * @return the modifyTime
	 */
	public Timestamp getModifyTime() {
		return modifyTime;
	}
	/**
	 * @param modifyTime the modifyTime to set
	 */
	public void setModifyTime(Timestamp modifyTime) {
		this.modifyTime = modifyTime;
	}
	/**
	 * @return the state
	 */
	public String getState() {
		return state;
	}
	/**
	 * @param state the state to set
	 */
	public void setState(String state) {
		this.state = state;
	}
	/**
	 * @return the price
	 */
	public String getPrice() {
		return price;
	}
	/**
	 * @param price the price to set
	 */
	public void setPrice(String price) {
		this.price = price;
	}
	/**
	 * @return the entryCount
	 */
	public String getEntryCount() {
		return entryCount;
	}
	/**
	 * @param entryCount the entryCount to set
	 */
	public void setEntryCount(String entryCount) {
		this.entryCount = entryCount;
	}
	/**
	 * @return the category
	 */
	public String getCategory() {
		return category;
	}
	/**
	 * @param category the category to set
	 */
	public void setCategory(String category) {
		this.category = category;
	}
	/**
	 * @return the businessCode
	 */
	public String getBusinessCode() {
		return businessCode;
	}
	/**
	 * @param businessCode the businessCode to set
	 */
	public void setBusinessCode(String businessCode) {
		this.businessCode = businessCode;
	}
	/**
	 * @return the poSpecCode
	 */
	public String getPoSpecCode() {
		return poSpecCode;
	}
	/**
	 * @param poSpecCode the poSpecCode to set
	 */
	public void setPoSpecCode(String poSpecCode) {
		this.poSpecCode = poSpecCode;
	}
	/**
	 * @return the poSpecName
	 */
	public String getPoSpecName() {
		return poSpecName;
	}
	/**
	 * @param poSpecName the poSpecName to set
	 */
	public void setPoSpecName(String poSpecName) {
		this.poSpecName = poSpecName;
	}
	/**
	 * @return the operationCode
	 */
	public String getOperationCode() {
		return operationCode;
	}
	/**
	 * @param operationCode the operationCode to set
	 */
	public void setOperationCode(String operationCode) {
		this.operationCode = operationCode;
	}

	/**
	 * @return the serviceCode
	 */
	public String getServiceCode() {
		return serviceCode;
	}

	/**
	 * @param serviceCode the serviceCode to set
	 */
	public void setServiceCode(String serviceCode) {
		this.serviceCode = serviceCode;
	}

	/**
	 * @return the serviceName
	 */
	public String getServiceName() {
		return serviceName;
	}

	/**
	 * @param serviceName the serviceName to set
	 */
	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	/**
	 * @return the contentOrder
	 */
	public Integer getContentOrder() {
		return contentOrder;
	}

	/**
	 * @param contentOrder the contentOrder to set
	 */
	public void setContentOrder(Integer contentOrder) {
		this.contentOrder = contentOrder;
	}

	/**
	 * @return the posterWidthHeight
	 */
	public String getPosterWidthHeight() {
		return posterWidthHeight;
	}

	/**
	 * @param posterWidthHeight the posterWidthHeight to set
	 */
	public void setPosterWidthHeight(String posterWidthHeight) {
		this.posterWidthHeight = posterWidthHeight;
	}

	/**
	 * @return the vodFormat
	 */
	public String getVodFormat() {
		return vodFormat;
	}

	/**
	 * @param vodFormat the vodFormat to set
	 */
	public void setVodFormat(String vodFormat) {
		this.vodFormat = vodFormat;
	}

	/**
	 * @return the ottFormat
	 */
	public String getOttFormat() {
		return ottFormat;
	}

	/**
	 * @param ottFormat the ottFormat to set
	 */
	public void setOttFormat(String ottFormat) {
		this.ottFormat = ottFormat;
	}

	/**
	 * @return the firstSpell
	 */
	public String getFirstSpell() {
		return firstSpell;
	}

	/**
	 * @param firstSpell the firstSpell to set
	 */
	public void setFirstSpell(String firstSpell) {
		this.firstSpell = firstSpell;
	}

	/**
	 * @return the validStart
	 */
	public String getValidStart() {
		return validStart;
	}

	/**
	 * @param validStart the validStart to set
	 */
	public void setValidStart(String validStart) {
		this.validStart = validStart;
	}

	/**
	 * @return the validEnd
	 */
	public String getValidEnd() {
		return validEnd;
	}

	/**
	 * @param validEnd the validEnd to set
	 */
	public void setValidEnd(String validEnd) {
		this.validEnd = validEnd;
	}

	/**
	 * @return the genre
	 */
	public String getGenre() {
		return genre;
	}

	/**
	 * @param genre the genre to set
	 */
	public void setGenre(String genre) {
		this.genre = genre;
	}

	/**
	 * @return the productOfferingName
	 */
	public String getProductOfferingName() {
		return productOfferingName;
	}

	/**
	 * @param productOfferingName the productOfferingName to set
	 */
	public void setProductOfferingName(String productOfferingName) {
		this.productOfferingName = productOfferingName;
	}

	/**
	 * @return the providerId
	 */
	public String getProviderId() {
		return providerId;
	}

	/**
	 * @param providerId the providerId to set
	 */
	public void setProviderId(String providerId) {
		this.providerId = providerId;
	}

	/**
	 * @return the providerAssetId
	 */
	public String getProviderAssetId() {
		return providerAssetId;
	}

	/**
	 * @param providerAssetId the providerAssetId to set
	 */
	public void setProviderAssetId(String providerAssetId) {
		this.providerAssetId = providerAssetId;
	}
	private boolean compareTo(Object a, Object b){
		if(a == null && b == null)
			return true;
		else
			return a==null ? b.equals(a) : a.equals(b);
	}
	
	public boolean compareTo(AssetTransition obj) {		
		if (obj != null) {
			if ( compareTo(this.assetId, obj.assetId) &&
//				 compareTo(this.productCode, obj.productCode) &&
//				 compareTo(this.productOfferingCode, obj.productOfferingCode) &&
//				 compareTo(this.contentPackageCode, obj.contentPackageCode) &&
//				 compareTo(this.contentCode, obj.contentCode) &&
//				 compareTo(this.chargeType, obj.chargeType) &&
//				 compareTo(this.contentType, obj.contentType) &&
//				 compareTo(this.productType, obj.productType) &&
//				 compareTo(this.parentAssetId, obj.parentAssetId) &&
				 compareTo(this.assetName, obj.assetName) &&
				 compareTo(this.assetDesc, obj.assetDesc) &&
				 compareTo(this.title, obj.title) &&
				 compareTo(this.year, obj.year) &&
				 compareTo(this.keyword, obj.keyword) &&
				 compareTo(this.rating, obj.rating) &&
				 compareTo(this.runTime, obj.runTime) &&
				 compareTo(this.displayRunTime, obj.displayRunTime) &&
				 compareTo(this.posterUrl, obj.posterUrl) &&
				 compareTo(this.director, obj.director) &&
				 compareTo(this.actor, obj.actor) &&
				 compareTo(this.state, obj.state) &&
				 compareTo(this.price, obj.price) &&
				 compareTo(this.entryCount, obj.entryCount) &&
				 compareTo(this.category, obj.category) &&
//				 compareTo(this.businessCode, obj.businessCode) &&
//				 compareTo(this.poSpecCode, obj.poSpecCode) &&
//				 compareTo(this.poSpecName, obj.poSpecName) &&
//				 compareTo(this.operationCode, obj.operationCode) &&
//				 compareTo(this.serviceCode, obj.serviceCode) &&
//				 compareTo(this.serviceName, obj.serviceName) &&
//				 compareTo(this.contentOrder, obj.contentOrder) &&
//				 compareTo(this.posterWidthHeight, obj.posterWidthHeight) &&
//				 compareTo(this.vodFormat, obj.vodFormat) &&
//				 compareTo(this.ottFormat, obj.ottFormat) &&
//				 compareTo(this.firstSpell, obj.firstSpell) &&
//				 compareTo(this.validStart, obj.validStart) &&
//				 compareTo(this.validEnd, obj.validEnd) &&
				 compareTo(this.genre, obj.genre) &&
				 compareTo(this.providerId, obj.providerId) &&
				 compareTo(this.providerAssetId, obj.providerAssetId)
					) {
				return true;
			}
		}
		return false;
	}
	@Override
	public String toString() {
		return "["+assetId+","+assetName+","+assetDesc+","+title+","+year+","+keyword+","+rating+","+runTime+","
		+displayRunTime+","+posterUrl+","+director+","+actor+","+state+","+price+","+entryCount+","+category+","+operationCode+","
		+firstSpell+","+genre+","+providerId+","+providerAssetId+"]";
	}
	
}
